services:
  app:
    image: 3nd3r1/express-app:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 127.0.0.1:8080:8080
    container_name: express-app
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
